INSERT INTO world.zone (iso2,zone_short_name , zone_full_name, continent_id , ui_subregion_id, zone_type)
VALUES ('AF','Afghanistan','The Islamic Republic of Afghanistan',3,8,'Country'),
('AL','Albania','The Republic of Albania',5,5,'Country'),
('DZ','Algeria','The Peoples Democratic Republic of Algeria',1,1,'Country'),
('AD','Andorra','The Principality of Andorra',5,5,'Country'),
('AO','Angola','The Republic of Angola',1,1,'Country'),
('AG','Antigua and Barbuda','Antigua and Barbuda',6,10,'Country'),
('AR','Argentina','The Argentine Republic',7,7,'Country'),
('AM','Armenia','The Republic of Armenia',5,5,'Country'),
('AU','Australia','Australia',4,4,'Country'),
('AT','Austria','The Republic of Austria',5,5,'Country'),
('AZ','Azerbaijan','The Republic of Azerbaijan',5,5,'Country'),
('BS','Bahamas','The Commonwealth of The Bahamas',6,10,'Country'),
('BH','Bahrain','The Kingdom of Bahrain',3,8,'Country'),
('BD','Bangladesh','The Peoples Republic of Bangladesh',3,3,'Country'),
('BB','Barbados','Barbados',6,10,'Country'),
('BY','Belarus','The Republic of Belarus',5,5,'Country'),
('BE','Belgium','The Kingdom of Belgium',5,5,'Country'),
('BZ','Belize','Belize',6,9,'Country'),
('BJ','Benin','The Republic of Benin',1,1,'Country'),
('BT','Bhutan','The Kingdom of Bhutan',3,3,'Country'),
('BO','Bolivia','The Plurinational State of Bolivia',7,7,'Country'),
('BA','Bosnia and Herzegovina','Bosnia and Herzegovina',5,5,'Country'),
('BW','Botswana','The Republic of Botswana',1,1,'Country'),
('BR','Brazil','The Federative Republic of Brazil',7,7,'Country'),
('BN','Brunei Darussalam','Brunei Darussalam',3,3,'Country'),
('BG','Bulgaria','The Republic of Bulgaria',5,5,'Country'),
('BF','Burkina Faso','Burkina Faso',1,1,'Country'),
('BI','Burundi','The Republic of Burundi',1,1,'Country'),
('CV','Cabo Verde','Republic of Cabo Verde',1,1,'Country'),
('KH','Cambodia','The Kingdom of Cambodia',3,3,'Country'),
('CM','Cameroon','The Republic of Cameroon',1,1,'Country'),
('CA','Canada','Canada',6,6,'Country'),
('CF','Central African Republic','The Central African Republic',1,1,'Country'),
('TD','Chad','The Republic of Chad',1,1,'Country'),
('CL','Chile','The Republic of Chile',7,7,'Country'),
('CN','China','The Peoples Republic of China',3,3,'Country'),
('CO','Colombia','The Republic of Colombia',7,7,'Country'),
('KM','Comoros','The Union of The Comoros',1,1,'Country'),
('CG','Republic of Congo','Republic of The Congo',1,1,'Country'),
('CR','Costa Rica','The Republic of Costa Rica',6,9,'Country'),
('HR','Croatia','The Republic of Croatia',5,5,'Country'),
('CU','Cuba','The Republic of Cuba',6,10,'Country'),
('CY','Cyprus','The Republic of Cyprus',5,8,'Country'),
('CZ','Czechia','The Czech Republic',5,5,'Country'),
('CI','Ivory Coast','The Republic of Côte dIvoire',1,1,'Country'),
('KP','North Korea','The Democratic Peoples Republic of Korea',3,3,'Country'),
('CD','Democratic Republic of The Congo','Democratic Republic of The Congo',1,1,'Country'),
('DK','Denmark','The Kingdom of Denmark',5,5,'Country'),
('DJ','Djibouti','The Republic of Djibouti',1,1,'Country'),
('DM','Dominica','The Commonwealth of Dominica',6,10,'Country'),
('DO','Dominican Republic','The Dominican Republic',6,10,'Country'),
('EC','Ecuador','The Republic of Ecuador',7,7,'Country'),
('EG','Egypt','The Arab Republic of Egypt',1,8,'Country'),
('SV','El Salvador','The Republic of El Salvador',6,9,'Country'),
('GQ','Equatorial Guinea','The Republic of Equatorial Guinea',1,1,'Country'),
('ER','Eritrea','The State of Eritrea',1,1,'Country'),
('EE','Estonia','The Republic of Estonia',5,5,'Country'),
('SZ','Eswatini','The Kingdom of Eswatini',1,1,'Country'),
('ET','Ethiopia','The Federal Democratic Republic of Ethiopia',1,1,'Country'),
('FJ','Fiji','The Republic of Fiji',4,4,'Country'),
('FI','Finland','The Republic of Finland',5,5,'Country'),
('FR','France','The French Republic',5,5,'Country'),
('GA','Gabon','The Gabonese Republic',1,1,'Country'),
('GM','Gambia','The Republic of The Gambia',1,1,'Country'),
('GE','Georgia','Georgia',5,5,'Country'),
('DE','Germany','The Federal Republic of Germany',5,5,'Country'),
('GH','Ghana','The Republic of Ghana',1,1,'Country'),
('GR','Greece','The Hellenic Republic',5,5,'Country'),
('GL','Greenland','Kalaallit Nunaat',6,6,'Country'),
('GD','Grenada','Grenada',6,10,'Country'),
('GT','Guatemala','The Republic of Guatemala',6,9,'Country'),
('GN','Guinea','The Republic of Guinea',1,1,'Country'),
('GW','Guinea-Bissau','The Republic of Guinea-Bissau',1,1,'Country'),
('GY','Guyana','The Republic of Guyana',7,7,'Country'),
('HT','Haiti','The Republic of Haiti',6,10,'Country'),
('HN','Honduras','The Republic of Honduras',6,9,'Country'),
('HU','Hungary','Hungary',5,5,'Country'),
('IS','Iceland','The Republic of Iceland',5,5,'Country'),
('IN','India','The Republic of India',3,3,'Country'),
('ID','Indonesia','The Republic of Indonesia',3,3,'Country'),
('IR','Iran','The Islamic Republic of Iran',3,8,'Country'),
('IQ','Iraq','The Republic of Iraq',3,8,'Country'),
('IE','Ireland','Ireland',5,5,'Country'),
('IL','Israel','The State of Israel',3,8,'Country'),
('IT','Italy','The Republic of Italy',5,5,'Country'),
('JM','Jamaica','Jamaica',6,10,'Country'),
('JP','Japan','Japan',3,3,'Country'),
('JO','Jordan','The Hashemite Kingdom of Jordan',3,8,'Country'),
('KZ','Kazakhstan','The Republic of Kazakhstan',3,3,'Country'),
('KE','Kenya','The Republic of Kenya',1,1,'Country'),
('KI','Kiribati','The Republic of Kiribati',4,4,'Country'),
('KW','Kuwait','The State of Kuwait',3,8,'Country'),
('KG','Kyrgyzstan','The Kyrgyz Republic',3,3,'Country'),
('LA','Laos','The Lao Peoples Democratic Republic',3,3,'Country'),
('LV','Latvia','The Republic of Latvia',5,5,'Country'),
('LB','Lebanon','The Lebanese Republic',3,8,'Country'),
('LS','Lesotho','The Kingdom of Lesotho',1,1,'Country'),
('LR','Liberia','The Republic of Liberia',1,1,'Country'),
('LY','Libya','State of Libya',1,1,'Country'),
('LT','Lithuania','The Republic of Lithuania',5,5,'Country'),
('LU','Luxembourg','The Grand Duchy of Luxembourg',5,5,'Country'),
('MG','Madagascar','The Republic of Madagascar',1,1,'Country'),
('MW','Malawi','The Republic of Malawi',1,1,'Country'),
('MY','Malaysia','Malaysia',3,3,'Country'),
('MV','Maldives','The Republic of Maldives',3,3,'Country'),
('ML','Mali','The Republic of Mali',1,1,'Country'),
('MT','Malta','The Republic of Malta',5,5,'Country'),
('MH','Marshall Islands','The Republic of The Marshall Islands',4,4,'Country'),
('MR','Mauritania','The Islamic Republic of Mauritania',1,1,'Country'),
('MU','Mauritius','The Republic of Mauritius',1,1,'Country'),
('MX','Mexico','The United Mexican States',6,6,'Country'),
('FM','Micronesia','The Federated States of Micronesia',4,4,'Country'),
('MC','Monaco','The Principality of Monaco',5,5,'Country'),
('MN','Mongolia','Mongolia',3,3,'Country'),
('ME','Montenegro','Montenegro',5,5,'Country'),
('MA','Morocco','The Kingdom of Morocco',1,1,'Country'),
('MZ','Mozambique','The Republic of Mozambique',1,1,'Country'),
('MM','Myanmar','The Republic of The Union of Myanmar',3,3,'Country'),
('NA','Namibia','The Republic of Namibia',1,1,'Country'),
('NR','Nauru','The Republic of Nauru',4,4,'Country'),
('NP','Nepal','The Federal Democratic Republic of Nepal',3,3,'Country'),
('NL','NeTherlands','The Kingdom of The NeTherlands',5,5,'Country'),
('NZ','New Zealand','New Zealand',4,4,'Country'),
('NI','Nicaragua','The Republic of Nicaragua',6,9,'Country'),
('NE','Niger','The Republic of The Niger',1,1,'Country'),
('NG','Nigeria','The Federal Republic of Nigeria',1,1,'Country'),
('NU','Niue','Niue',4,4,'Country'),
('NO','Norway','The Kingdom of Norway',5,5,'Country'),
('OM','Oman','The Sultanate of Oman',3,8,'Country'),
('PK','Pakistan','The Islamic Republic of Pakistan',3,3,'Country'),
('PW','Palau','The Republic of Palau',4,4,'Country'),
('PA','Panama','The Republic of Panama',6,9,'Country'),
('PG','Papua New Guinea','Independent State of Papua New Guinea',4,4,'Country'),
('PY','Paraguay','The Republic of Paraguay',7,7,'Country'),
('PE','Peru','The Republic of Peru',7,7,'Country'),
('PH','Philippines','The Republic of The Philippines',3,3,'Country'),
('TW','Taiwan','Republic of China',3,3,'Country'),
('PL','Poland','The Republic of Poland',5,5,'Country'),
('PT','Portugal','The Portuguese Republic',5,5,'Country'),
('QA','Qatar','The State of Qatar',3,8,'Country'),
('KR','South Korea','The Republic of Korea',3,3,'Country'),
('MD','Moldova','The Republic of Moldova',5,5,'Country'),
('RO','Romania','Romania',5,5,'Country'),
('RU','Russia','The Russian Federation',5,5,'Country'),
('RW','Rwanda','The Republic of Rwanda',1,1,'Country'),
('KN','Saint Kitts and Nevis','Saint Kitts and Nevis',6,10,'Country'),
('LC','Saint Lucia','Saint Lucia',6,10,'Country'),
('VC','Saint Vincent and The Grenadines','Saint Vincent and The Grenadines',6,10,'Country'),
('WS','Samoa','The Independent State of Samoa',4,4,'Country'),
('SM','San Marino','The Republic of San Marino',5,5,'Country'),
('ST','Sao Tome and Principe','The Democratic Republic of Sao Tome and Principe',1,1,'Country'),
('SA','Saudi Arabia','The Kingdom of Saudi Arabia',3,3,'Country'),
('SN','Senegal','The Republic of Senegal',1,1,'Country'),
('RS','Serbia','The Republic of Serbia',5,5,'Country'),
('SC','Seychelles','The Republic of Seychelles',1,1,'Country'),
('SL','Sierra Leone','The Republic of Sierra Leone',1,1,'Country'),
('SG','Singapore','The Republic of Singapore',3,3,'Country'),
('SK','Slovakia','The Slovak Republic',5,5,'Country'),
('SI','Slovenia','The Republic of Slovenia',5,5,'Country'),
('SB','Solomon Islands','Solomon Islands',4,4,'Country'),
('SO','Somalia','The Federal Republic of Somalia',1,1,'Country'),
('ZA','South Africa','The Republic of South Africa',1,1,'Country'),
('SZ','Swaziland','Kingdom of Eswatini',1,1,'Country'),
('SS','South Sudan','The Republic of South Sudan',1,1,'Country'),
('ES','Spain','The Kingdom of Spain',5,5,'Country'),
('LK','Sri Lanka','The Democratic Socialist Republic of Sri Lanka',3,3,'Country'),
('SD','Sudan','The Republic of The Sudan',1,1,'Country'),
('SR','Suriname','The Republic of Suriname',7,7,'Country'),
('SE','Sweden','The Kingdom of Sweden',5,5,'Country'),
('CH','Switzerland','The Swiss Confederation',5,5,'Country'),
('SY','Syria','The Syrian Arab Republic',3,8,'Country'),
('TJ','Tajikistan','The Republic of Tajikistan',3,3,'Country'),
('TH','Thailand','The Kingdom of Thailand',3,3,'Country'),
('MK','Macedonia','The former Yugoslav Republic of Macedonia',5,5,'Country'),
('TL','Timor-Leste','The Democratic Republic of Timor-Leste',3,3,'Country'),
('TG','Togo','The Togolese Republic',1,1,'Country'),
('TO','Tonga','The Kingdom of Tonga',4,4,'Country'),
('TT','Trinidad and Tobago','The Republic of Trinidad and Tobago',6,10,'Country'),
('TN','Tunisia','The Republic of Tunisia',1,1,'Country'),
('TR','Turkey','The Republic of Turkey',5,8,'Country'),
('TM','Turkmenistan','Turkmenistan',3,3,'Country'),
('TV','Tuvalu','Tuvalu',4,4,'Country'),
('UG','Uganda','The Republic of Uganda',1,1,'Country'),
('UA','Ukraine','Ukraine',5,5,'Country'),
('AE','United Arab Emirates','The United Arab Emirates',3,8,'Country'),
('GB','United Kingdom','The United Kingdom of Great Britain and NorThern Ireland',5,5,'Country'),
('TZ','Tanzania','The United Republic of Tanzania',1,1,'Country'),
('UY','Uruguay','The Eastern Republic of Uruguay',7,7,'Country'),
('UZ','Uzbekistan','The Republic of Uzbekistan',3,3,'Country'),
('VU','Vanuatu','The Republic of Vanuatu',4,4,'Country'),
('VE','Venezuela','The Bolivarian Republic of Venezuela',7,7,'Country'),
('VN','Vietnam','The Socialist Republic of Viet Nam',3,3,'Country'),
('YE','Yemen','The Republic of Yemen',3,8,'Country'),
('ZM','Zambia','The Republic of Zambia',1,1,'Country'),
('ZW','Zimbabwe','The Republic of Zimbabwe',1,1,'Country'),
('AL','Alabama','The State of Alabama','6','6','State'),
('AK','Alaska','The State of Alaska','6','6','State'),
('AZ','Arizona','The State of Arizona','6','6','State'),
('AR','Arkansas','The State of Arkansas','6','6','State'),
('CA','California','The State of California','6','6','State'),
('CO','Colorado','The State of Colorado','6','6','State'),
('CT','Connecticut','The State of Connecticut','6','6','State'),
('DE','Delaware','The State of Delaware','6','6','State'),
('FL','Florida','The State of Florida','6','6','State'),
('GA','Georgia','The State of Georgia','6','6','State'),
('HI','Hawaii','The State of Hawaii','6','6','State'),
('ID','Idaho','The State of Idaho','6','6','State'),
('IL','Illinois','The State of Illinois','6','6','State'),
('IN','Indiana','The State of Indiana','6','6','State'),
('IA','Iowa','The State of Iowa','6','6','State'),
('KS','Kansas','The State of Kansas','6','6','State'),
('KY','Kentucky','The State of Kentucky','6','6','State'),
('LA','Louisiana','The State of Louisiana','6','6','State'),
('ME','Maine','The State of Maine','6','6','State'),
('MD','Maryland','The State of Maryland','6','6','State'),
('MA','Massachusetts','The State of Massachusetts','6','6','State'),
('MI','Michigan','The State of Michigan','6','6','State'),
('MN','Minnesota','The State of Minnesota','6','6','State'),
('MS','Mississippi','The State of Mississippi','6','6','State'),
('MO','Missouri','The State of Missouri','6','6','State'),
('MT','Montana','The State of Montana','6','6','State'),
('NE','Nebraska','The State of Nebraska','6','6','State'),
('NV','Nevada','The State of Nevada','6','6','State'),
('NH','New Hampshire','The State of New Hampshire','6','6','State'),
('NJ','New Jersey','The State of New Jersey','6','6','State'),
('NM','New Mexico','The State of New Mexico','6','6','State'),
('NY','New York','The State of New York','6','6','State'),
('NC','North Carolina','The State of North Carolina','6','6','State'),
('ND','North Dakota','The State of North Dakota','6','6','State'),
('OH','Ohio','The State of Ohio','6','6','State'),
('OK','Oklahoma','The State of Oklahoma','6','6','State'),
('OR','Oregon','The State of Oregon','6','6','State'),
('PA','Pennsylvania','The State of Pennsylvania','6','6','State'),
('RI','Rhode Island','The State of Rhode Island','6','6','State'),
('SC','South Carolina','The State of South Carolina','6','6','State'),
('SD','South Dakota','The State of South Dakota','6','6','State'),
('TN','Tennessee','The State of Tennessee','6','6','State'),
('TX','Texas','The State of Texas','6','6','State'),
('UT','Utah','The State of Utah','6','6','State'),
('VT','Vermont','The State of Vermont','6','6','State'),
('VA','Virginia','The State of Virginia','6','6','State'),
('WA','Washington','The State of Washington','6','6','State'),
('WV','West Virginia','The State of West Virginia','6','6','State'),
('WI','Wisconsin','The State of Wisconsin','6','6','State'),
('WY','Wyoming','The State of Wyoming','6','6','State'),
('AS','American Samoa','The Territory of American Samoa','8','4','Territory'),
('GU','Guam','The Territory of Guam','8','4','Territory'),
('MP','Northern Mariana Islands','The Territory of Northern Mariana Islands','8','4','Territory'),
('PR','Puerto Rico','The Territory of Puerto Rico','6','10','Territory'),
('VI','U.S. Virgin Islands','The Territory of U.S. Virgin Islands','6','10','Territory'),
('ES','Western Sahara','Western Sahara','1','1','Disputed Territory')