INSERT INTO world.country (iso2,country_short_name , country_full_name, continent_id , ui_subregion_id)
VALUES ('AF','Afghanistan','The Islamic Republic of Afghanistan',3,8),
('AL','Albania','The Republic of Albania',5,5),
('DZ','Algeria','The Peoples Democratic Republic of Algeria',1,1),
('AD','Andorra','The Principality of Andorra',5,5),
('AO','Angola','The Republic of Angola',1,1),
('AG','Antigua and Barbuda','Antigua and Barbuda',6,10),
('AR','Argentina','The Argentine Republic',7,7),
('AM','Armenia','The Republic of Armenia',5,5),
('AU','Australia','Australia',4,4),
('AT','Austria','The Republic of Austria',5,5),
('AZ','Azerbaijan','The Republic of Azerbaijan',5,5),
('BS','Bahamas','The Commonwealth of The Bahamas',6,10),
('BH','Bahrain','The Kingdom of Bahrain',3,8),
('BD','Bangladesh','The Peoples Republic of Bangladesh',3,3),
('BB','Barbados','Barbados',6,10),
('BY','Belarus','The Republic of Belarus',5,5),
('BE','Belgium','The Kingdom of Belgium',5,5),
('BZ','Belize','Belize',6,9),
('BJ','Benin','The Republic of Benin',1,1),
('BT','Bhutan','The Kingdom of Bhutan',3,3),
('BO','Bolivia','The Plurinational State of Bolivia',7,7),
('BA','Bosnia and Herzegovina','Bosnia and Herzegovina',5,5),
('BW','Botswana','The Republic of Botswana',1,1),
('BR','Brazil','The Federative Republic of Brazil',7,7),
('BN','Brunei Darussalam','Brunei Darussalam',3,3),
('BG','Bulgaria','The Republic of Bulgaria',5,5),
('BF','Burkina Faso','Burkina Faso',1,1),
('BI','Burundi','The Republic of Burundi',1,1),
('CV','Cabo Verde','Republic of Cabo Verde',1,1),
('KH','Cambodia','The Kingdom of Cambodia',3,3),
('CM','Cameroon','The Republic of Cameroon',1,1),
('CA','Canada','Canada',6,6),
('CF','Central African Republic','The Central African Republic',1,1),
('TD','Chad','The Republic of Chad',1,1),
('CL','Chile','The Republic of Chile',7,7),
('CN','China','The Peoples Republic of China',3,3),
('CO','Colombia','The Republic of Colombia',7,7),
('KM','Comoros','The Union of The Comoros',1,1),
('CG','Congo','The Republic of The Congo',1,1),
('CR','Costa Rica','The Republic of Costa Rica',6,9),
('HR','Croatia','The Republic of Croatia',5,5),
('CU','Cuba','The Republic of Cuba',6,10),
('CY','Cyprus','The Republic of Cyprus',5,8),
('CZ','Czechia','The Czech Republic',5,5),
('CI','Ivory Coast','The Republic of Côte dIvoire',1,1),
('KP','North Korea','The Democratic Peoples Republic of Korea',3,3),
('CD','Democratic Republic of The Congo','The Democratic Republic of The Congo',1,1),
('DK','Denmark','The Kingdom of Denmark',5,5),
('DJ','Djibouti','The Republic of Djibouti',1,1),
('DM','Dominica','The Commonwealth of Dominica',6,10),
('DO','Dominican Republic','The Dominican Republic',6,10),
('EC','Ecuador','The Republic of Ecuador',7,7),
('EG','Egypt','The Arab Republic of Egypt',1,8),
('SV','El Salvador','The Republic of El Salvador',6,9),
('GQ','Equatorial Guinea','The Republic of Equatorial Guinea',1,1),
('ER','Eritrea','The State of Eritrea',1,1),
('EE','Estonia','The Republic of Estonia',5,5),
('SZ','Eswatini','The Kingdom of Eswatini',1,1),
('ET','Ethiopia','The Federal Democratic Republic of Ethiopia',1,1),
('FJ','Fiji','The Republic of Fiji',4,4),
('FI','Finland','The Republic of Finland',5,5),
('FR','France','The French Republic',5,5),
('GA','Gabon','The Gabonese Republic',1,1),
('GM','Gambia','The Republic of The Gambia',1,1),
('GE','Georgia','Georgia',5,5),
('DE','Germany','The Federal Republic of Germany',5,5),
('GH','Ghana','The Republic of Ghana',1,1),
('GR','Greece','The Hellenic Republic',5,5),
('GD','Grenada','Grenada',6,10),
('GT','Guatemala','The Republic of Guatemala',6,9),
('GN','Guinea','The Republic of Guinea',1,1),
('GW','Guinea-Bissau','The Republic of Guinea-Bissau',1,1),
('GY','Guyana','The Republic of Guyana',7,7),
('HT','Haiti','The Republic of Haiti',6,10),
('HN','Honduras','The Republic of Honduras',6,9),
('HU','Hungary','Hungary',5,5),
('IS','Iceland','The Republic of Iceland',5,5),
('IN','India','The Republic of India',3,3),
('ID','Indonesia','The Republic of Indonesia',3,3),
('IR','Iran','The Islamic Republic of Iran',3,8),
('IQ','Iraq','The Republic of Iraq',3,8),
('IE','Ireland','Ireland',5,5),
('IL','Israel','The State of Israel',3,8),
('IT','Italy','The Republic of Italy',5,5),
('JM','Jamaica','Jamaica',6,10),
('JP','Japan','Japan',3,3),
('JO','Jordan','The Hashemite Kingdom of Jordan',3,8),
('KZ','Kazakhstan','The Republic of Kazakhstan',3,3),
('KE','Kenya','The Republic of Kenya',1,1),
('KI','Kiribati','The Republic of Kiribati',4,4),
('KW','Kuwait','The State of Kuwait',3,8),
('KG','Kyrgyzstan','The Kyrgyz Republic',3,3),
('LA','Laos','The Lao Peoples Democratic Republic',3,3),
('LV','Latvia','The Republic of Latvia',5,5),
('LB','Lebanon','The Lebanese Republic',3,8),
('LS','Lesotho','The Kingdom of Lesotho',1,1),
('LR','Liberia','The Republic of Liberia',1,1),
('LY','Libya','State of Libya',1,1),
('LT','Lithuania','The Republic of Lithuania',5,5),
('LU','Luxembourg','The Grand Duchy of Luxembourg',5,5),
('MG','Madagascar','The Republic of Madagascar',1,1),
('MW','Malawi','The Republic of Malawi',1,1),
('MY','Malaysia','Malaysia',3,3),
('MV','Maldives','The Republic of Maldives',3,3),
('ML','Mali','The Republic of Mali',1,1),
('MT','Malta','The Republic of Malta',5,5),
('MH','Marshall Islands','The Republic of The Marshall Islands',4,4),
('MR','Mauritania','The Islamic Republic of Mauritania',1,1),
('MU','Mauritius','The Republic of Mauritius',1,1),
('MX','Mexico','The United Mexican States',6,6),
('FM','Micronesia','The Federated States of Micronesia',4,4),
('MC','Monaco','The Principality of Monaco',5,5),
('MN','Mongolia','Mongolia',3,3),
('ME','Montenegro','Montenegro',5,5),
('MA','Morocco','The Kingdom of Morocco',1,1),
('MZ','Mozambique','The Republic of Mozambique',1,1),
('MM','Myanmar','The Republic of The Union of Myanmar',3,3),
('NA','Namibia','The Republic of Namibia',1,1),
('NR','Nauru','The Republic of Nauru',4,4),
('NP','Nepal','The Federal Democratic Republic of Nepal',3,3),
('NL','NeTherlands','The Kingdom of The NeTherlands',5,5),
('NZ','New Zealand','New Zealand',4,4),
('NI','Nicaragua','The Republic of Nicaragua',6,9),
('NE','Niger','The Republic of The Niger',1,1),
('NG','Nigeria','The Federal Republic of Nigeria',1,1),
('NU','Niue','Niue',4,4),
('NO','Norway','The Kingdom of Norway',5,5),
('OM','Oman','The Sultanate of Oman',3,8),
('PK','Pakistan','The Islamic Republic of Pakistan',3,3),
('PW','Palau','The Republic of Palau',4,4),
('PA','Panama','The Republic of Panama',6,9),
('PG','Papua New Guinea','Independent State of Papua New Guinea',4,4),
('PY','Paraguay','The Republic of Paraguay',7,7),
('PE','Peru','The Republic of Peru',7,7),
('PH','Philippines','The Republic of The Philippines',3,3),
('PL','Poland','The Republic of Poland',5,5),
('PT','Portugal','The Portuguese Republic',5,5),
('QA','Qatar','The State of Qatar',3,8),
('KR','South Korea','The Republic of Korea',3,3),
('MD','Moldova','The Republic of Moldova',5,5),
('RO','Romania','Romania',5,5),
('RU','Russian Federation','The Russian Federation',5,5),
('RW','Rwanda','The Republic of Rwanda',1,1),
('KN','Saint Kitts and Nevis','Saint Kitts and Nevis',6,10),
('LC','Saint Lucia','Saint Lucia',6,10),
('VC','Saint Vincent and The Grenadines','Saint Vincent and The Grenadines',6,10),
('WS','Samoa','The Independent State of Samoa',4,4),
('SM','San Marino','The Republic of San Marino',5,5),
('ST','Sao Tome and Principe','The Democratic Republic of Sao Tome and Principe',1,1),
('SA','Saudi Arabia','The Kingdom of Saudi Arabia',3,3),
('SN','Senegal','The Republic of Senegal',1,1),
('RS','Serbia','The Republic of Serbia',5,5),
('SC','Seychelles','The Republic of Seychelles',1,1),
('SL','Sierra Leone','The Republic of Sierra Leone',1,1),
('SG','Singapore','The Republic of Singapore',3,3),
('SK','Slovakia','The Slovak Republic',5,5),
('SI','Slovenia','The Republic of Slovenia',5,5),
('SB','Solomon Islands','Solomon Islands',4,4),
('SO','Somalia','The Federal Republic of Somalia',1,1),
('ZA','South Africa','The Republic of South Africa',1,1),
('SS','South Sudan','The Republic of South Sudan',1,1),
('ES','Spain','The Kingdom of Spain',5,5),
('LK','Sri Lanka','The Democratic Socialist Republic of Sri Lanka',3,3),
('SD','Sudan','The Republic of The Sudan',1,1),
('SR','Suriname','The Republic of Suriname',7,7),
('SE','Sweden','The Kingdom of Sweden',5,5),
('CH','Switzerland','The Swiss Confederation',5,5),
('SY','Syria','The Syrian Arab Republic',3,8),
('TJ','Tajikistan','The Republic of Tajikistan',3,3),
('TH','Thailand','The Kingdom of Thailand',3,3),
('MK','Macedonia','The former Yugoslav Republic of Macedonia',5,5),
('TL','Timor-Leste','The Democratic Republic of Timor-Leste',3,3),
('TG','Togo','The Togolese Republic',1,1),
('TO','Tonga','The Kingdom of Tonga',4,4),
('TT','Trinidad and Tobago','The Republic of Trinidad and Tobago',6,10),
('TN','Tunisia','The Republic of Tunisia',1,1),
('TR','Turkey','The Republic of Turkey',5,8),
('TM','Turkmenistan','Turkmenistan',3,3),
('TV','Tuvalu','Tuvalu',4,4),
('UG','Uganda','The Republic of Uganda',1,1),
('UA','Ukraine','Ukraine',5,5),
('AE','United Arab Emirates','The United Arab Emirates',3,8),
('GB','United Kingdom','The United Kingdom of Great Britain and NorThern Ireland',5,5),
('TZ','Tanzania','The United Republic of Tanzania',1,1),
('US','United States of America','The United States of America',6,6),
('UY','Uruguay','The Eastern Republic of Uruguay',7,7),
('UZ','Uzbekistan','The Republic of Uzbekistan',3,3),
('VU','Vanuatu','The Republic of Vanuatu',4,4),
('VE','Venezuela','The Bolivarian Republic of Venezuela',7,7),
('VN','Vietnam','The Socialist Republic of Viet Nam',3,3),
('YE','Yemen','The Republic of Yemen',3,8),
('ZM','Zambia','The Republic of Zambia',1,1),
('ZW','Zimbabwe','The Republic of Zimbabwe',1,1)